NewCar:
    trainer: ppo
    batch_size: 512
    beta: 1e-3
    buffer_size: 5120
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 1.0e6
    normalize: true
    num_epoch: 8
    num_layers: 2
    time_horizon: 256
    summary_freq: 5000
    use_recurrent: false
    sequence_length: 64
    memory_size: 128
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.01
            gamma: 0.99
            encoding_size: 256